title: Just Another Microblog 
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Everything related to software development and beyond
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vglushko.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true
excerpt_separator: <!--more-->

minima:
  skin: dark
  social_links:
    twitter: vglushko
    linkedin: vitaliy-glushko-68b89721

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
