theme: jekyll-theme-cayman
title: Software Architecture, Development, Deployment, Team Leadership
description: Microblog on everything related to software development

collections:
  posts:
    permalink: /:year/:month/:day/:title
    output: true